Comment: >
  # This trains the baseline model (fast_dev_run is a debugging flag)
  python run.py --config-name="baseline_gru" trainer_cfg.fast_dev_run=1
  # Overfit in 1 batch
  python run.py --config-name="baseline_gru" trainer_cfg.limit_train_batches=1 trainer_cfg.limit_val_batches=1 trainer_cfg.limit_test_batches=1 trainer_cfg.log_every_n_steps=1

project_name: "speech_bci"
experiment_name: "baseline_gru"


common:
  #outputDir: "/Users/ekellbuch/Projects/deepseq/bci/neural_seq_decoder/outputs"
  #datasetPath: &datasetPath "/Users/ekellbuch/datasets/SpeechBCI/competitionData/ptDecoder_ctc"
  outputDir: "/scratch/users/${oc.env:USER}/SpeechBCI/logs"
  datasetPath: &datasetPath "/scratch/groups/swl1/SpeechBCI/competitionData/ptDecoder_ctc"


data_cfg:
  batchSize: 64
  num_workers: 0
  datasetPath: *datasetPath
  # transformations:
  whiteNoiseSD: 0.8  # add white noise
  constantOffsetSD: 0.2  # add constant offset
  # masking
  mask_value: 0.0
  speckled_mask_p: 0
  feature_mask_p: 0
  temporal_mask_n: 0


# seqLen: 150 ? not used
# maxTimeSeriesLen: 1200 ? not used
seed: 0

module_cfg:
  type: "bci"

model_cfg:
  type: "bci_gru"
  configs:
    neural_dim: 256 #nInputFeatures
    n_classes: 40 #nClasses
    # gru params
    hidden_dim: 1024 #nUnits
    layer_dim: 5 #nLayers
    dropout: 0.4
    bidirectional: true
    # base decoder parameters:
    gaussianSmoothWidth: 2.0
    unfolding: true
    strideLen: 4
    kernelLen: 32

optimizer_cfg:
  type: "adam"
  configs:
    lr: 0.02  # lrStart
    betas: [0.9, 0.999]
    eps: 0.1
    weight_decay: 1e-5  #l2_decay

scheduler_cfg:
  type: "linear"
  interval: "step"
  frequency: 1
  configs:
    start_factor : 1.0
    end_factor: 1.0

callbacks:
  lr_monitor:
    logging_interval: "step"
  grad_norm:
    type:

  

trainer_cfg:
  fast_dev_run: false
  logger: "wandb"
  accelerator: "auto"
  max_steps: 10000
  log_every_n_steps: 100
  limit_test_batches:
  limit_train_batches:
  limit_val_batches:
  max_epochs:


eval_cfg:

hydra:
  run:
    dir: ./outputs/${now:%y-%m-%d}/${now:%H-%M-%S}
