Comment: >
  # This trains the baseline model
  python run.py --config-name="baseline_mamba" trainer_cfg.fast_dev_run=1

project_name: "speech_bci"
experiment_name: "baseline_mamba"


common:
  #outputDir: "/Users/ekellbuch/Projects/deepseq/bci/neural_seq_decoder/outputs"
  #datasetPath: &datasetPath "/Users/ekellbuch/datasets/SpeechBCI/competitionData/ptDecoder_ctc"
  outputDir: "/scratch/users/${oc.env:USER}/SpeechBCI/logs"
  datasetPath: &datasetPath "/scratch/groups/swl1/SpeechBCI/competitionData/ptDecoder_ctc"

module_cfg:
  type: "bci"

data_cfg:
  batchSize: 64
  datasetPath: *datasetPath
  whiteNoiseSD: 0.8
  constantOffsetSD: 0.2
  # masking
  mask_value: 0.0
  speckled_mask_p: 0.45
  renormalize_masking: false
  feature_mask_p: 0.03
  temporal_mask_n: 1
  temporal_mask_len: 2
  num_workers: 16


# maxTimeSeriesLen: 1200 ? not used
lrEnd: 0.02
nBatch: 8000  # 3000
seed: 15

model_cfg:
  type: "bci_mamba"
  configs:
    neural_dim: 256 #nInputFeatures
    n_classes: 40 #nClasses
    layer_dim: 6 #nLayers
    #nDays:   # size of training data
    strideLen: 4
    kernelLen: 32
    gaussianSmoothWidth: 2.0
    bidirectional: true
    # mamba params
    d_model: 1024
    d_state: 16
    d_conv: 4
    expand_factor: 1
    bidirectional_input: false

optimizer_cfg:
  type: "adam"
  configs:
    lr: 0.01  # lrStart
    betas: [0.9, 0.99]
    eps: 0.1
    weight_decay: 1e-5  #l2_decay

scheduler_cfg:
  type: "stepLR"
  configs:
    step_size : 6101
    gamma: 0.01

callbacks:
  lr_monitor:
    logging_interval: "step"
  grad_norm:
    type:

trainer_cfg:
  fast_dev_run: false
  logger: "wandb"
  accelerator: "auto"
  max_steps: 10000
  log_every_n_steps: 100
  gradient_clip_val: 0 #.0
  gradient_clip_algorithm: "norm"



eval_cfg:

hydra:
  run:
    dir: ./outputs/${now:%y-%m-%d}/${now:%H-%M-%S}
